### ISSUE TITLE
Converting circular structure to JSON - Redis

### ISSUE THREAD

**Issue by fgiaretta** [kwhitley/apicache#100]
If the JSON contains circular structure, the application breaks down, one solution would be to apply JSON.decycle before saving in Redis

[JSON.decycle](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js)

apicache.js - Line 267
```javascript
globalOptions.redisClient.hset(key, "responseObj", JSON.stringify(JSON.decycle(responseObj)));
```

**Comment by kwhitley** [comment]
Thanks @fgiaretta - I'll roll that into the next release... we're still working on a restify/node 7.7+ conflict!

**Comment by kwhitley** [comment]
EDIT: Actually, as that's not a built-in JSON function (and thus would require dependencies to fix), I'm going to leave that out for now unless this gets more upvotes.
