### ISSUE TITLE
apicache.clear with Redis behaviour

### ISSUE THREAD

**Issue by shershen08** [kwhitley/apicache#102]
I am using apicache with Redis cache via redislabs.com account. The caching part works fine, results are visible in the Redislabs dashboard and data is retrieved fine.
But when it comes to clearing the cache it doesn't seem to work for me:
 
 - calling `apicache.clear(); ` in one of my controllers however after that the redislabs dashboard  shows the same amount of data in the redis.
 - I've also tried to perform `apicache.getIndex()` but I get empty object there.

**Comment by shershen08** [comment]
Seem that using apicache API directly for clearing a Redis cache is not a solution so I ad doing it this way:

```
//create standalone Redis connection
let redisConnection = redis.createClient(<config object>);

//use it for apicache
let cacheWithRedis = apicache
	.options({redisClient: redisConnection})
	.middleware
//..
//later where we need to access Redis directly
redisConnection.keys("*", function(err, keys) {
      //keys
});

redisConnection.flushdb(function(err) {
    //void
});
```

**Comment by cmosgh** [comment]
Maybe you should use something like: 
```
apicache.options({
    headers: {
      "cache-control": "no-cache"
    },
    redisClient
  }).clear(apiCahceGroupName);
```

**Comment by kwhitley** [comment]
Future cache stores implementations will be responsible for clearing themselves, allowing external hooks for clearing themselves, etc.  Will close this for now until then, as I'd rather not continue to grow the current rather fragile and conditional codebase!
