### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by rijkvanzanten** [kwhitley/apicache#104]
Hey!

I just wanted to thank you for this great package.

Keep on making awesome stuff ✨🚀 

Cheers!

**Comment by kwhitley** [comment]
@svozza @ubergesundheit @vectart @rutgernation @Amri91 @ashwinnaidu @agolden @enricsangra @nmors @viebel @plck @davidyang @tskillian @peteboere @briangonzalez @danielsogl @lukechilds @conmarap @gesposito 

This thank you is really for you guys and all your work making this library as robust as it is!  ❤️  Here's to the next version!
