### ISSUE TITLE
Modify cache TTL in request handler

### ISSUE THREAD

**Issue by jayjanssen** [kwhitley/apicache#105]
Hi, wondering if something like this is already possible.  If not, then a feature request perhaps for 1.0.  Awesome module, BTW -- was exactly what I'm looking for.  

```
let cache = apicache.middleware

app.use(cache('5 minutes'))

app.get('/will-be-cached', (req, res) => {
  if (some_exception) {
     res.cache_ttl = '10 minutes'
  } 
  res.json({ success: true })
})
```

**Comment by kwhitley** [comment]
@jayjanssen If you want to overwrite the default headers (including the ones like `cache-control` injected by apicache), you have up until the final `res.send/res.json/res.end` call to do so.  That said, the headers you inject will be cached with the response for rebuilding/serving subsequent requests, so be careful with this!

Also, the whole point of this/caching is to prevent the logic inside the route from firing on a cache hit - thus whatever the route finally serves (the first time), is served for all future requests until the entry expires.

Hope this helps!

**Comment by jayjanssen** [comment]
@kwhitley  appreciate the response.   I do see that I can override the cache-control header, but is it possible to change the actual TTL used in redis for the response?
