### ISSUE TITLE
Local settings are not overriding global settings

### ISSUE THREAD

**Issue by ghost** [kwhitley/apicache#115]
```js
const apiCache = require('apicache');
const redisClient = require('../configurators/redis');

const gloablOptions = {
  redisClient,
  debug: true,
  statusCodes: {
      include: [200, 304]
  }
};

const cache = apiCache.options(gloablOptions);

module.exports = ({time, options={}}) => {
    return cache.middleware(time, req =>  req.method == 'GET', Object.assign(gloablOptions, options));
};
```

Anything wrong with the code?

**Comment by kwhitley** [comment]
@jatin-furlenco Not sure what you're trying to do there really, but I will say there's no need to Object.assign it like that...

```js
const apicache = require('apicache').options({
  redisClient,
  debug: true,
  statusCodes: {
    include: [200, 304]
  }
})

apicache.middleware('1 hour', req => req.method === 'GET', { debug: false }) // will merge these with the global options
```

**Comment by jatin-furlenco** [comment]
my express-routes have different `appendKey` options. So i am passing these options to the function. While doing this my globalOptions are overridden by localOptions for all the routes.

**Comment by kwhitley** [comment]
So based on your code @ghost, it should all work if you simply replace the last bit with:

```js
module.exports = ({time, options={}}) => {
    return cache.middleware(time, req =>  req.method == 'GET', options);
};
```

The `Object.assign` is unneeded as it happens internally.  In this case, the local options should definitely override the global ones, per the current test coverage.  If you find that it is not, please re-open the issue and we'll discuss!
