### ISSUE TITLE
Clearing cache target does not clear automatic expiration.

### ISSUE THREAD

**Issue by RowanMeara** [kwhitley/apicache#118]
If a cache entry is cleared manually before it automatically expires, the automatic clear will still run.  Thus, if you periodically clear and refresh cache entries, they will also be periodically clobbered by the still existing automatic expiration functions from the manually cleared entries.  One workaround is to set the duration very high so that the automatic Timers will never run, but that is not great because the process is essentially leaking memory.

The problematic Timer is created by line 130 below which creates a Timer to clear the cache but features no way to cancel that Timer if the cache is manually cleared before the Timer fires.

https://github.com/kwhitley/apicache/blob/bad8734832ad8ff589018eb261c14fedecc8b688/src/apicache.js#L113-L131

**Comment by kwhitley** [comment]
Will go out in v.1.1.1!
