### ISSUE TITLE
accumulateContent throws "list argument must be an Array of Buffers" exception

### ISSUE THREAD

**Issue by dberke711** [kwhitley/apicache#123]
On line 142, It appears that oldContent can be a string and not a Buffer - this throws an exception in Buffer.concat().  

Checking if oldContent is a string and converting it to a Buffer if so fixes the issue.

**Comment by eliprand** [comment]
FWIW, we were getting this error too.
We upgraded to node `v8.11.2` and it went away. We were planning on upgrading anyways, so no biggie for us.

**Comment by apascal** [comment]
Hi @kwhitley, we ran into the same problem and realized it was fixed on `master`, but no `v1.2.4` was published.
Do you plan on releasing an NPM version including this fix ?
