### ISSUE TITLE
Content-Encoding Error with compression and route caching

### ISSUE THREAD

**Issue by elodingens** [kwhitley/apicache#124]
Hi,

we have a strange error in our application with the apicache. 

If I enable the apicache global in our application everything works fine.

```
const cacheTime = '5 minutes';
const cache = apicache.middleware;
const cacheGroupKey = 'internal';

app.use(compression());

app.use(cache(cacheTime));
apicache.options({
  debug: true,
  enabled: true,
  statusCodes: {
    include: [200],
  },
});

app.use('/api', (req, res) => {
  if (!checkPreviewAllowed(req, res)) {
      return;
  }
  req.apicacheGroup = cacheGroupKey;
  proxy.web(req, res, {target: targetUrl});
});
```

1. Call /api/merchant/de => ``` [apicache] group detected "internal"
 [apicache] adding cache entry for "/api/merchants/de" @ 5 minutes - 8.22sec```
=> json is shown
2. Call /api/merchant/de => ```[apicache] sending cached (memory-cache) version of /api/merchants/de - 0ms```
=> json is shown

So now with route caching:
```
const cacheTime = '5 minutes';
const cache = apicache.middleware;
const cacheGroupKey = 'internal';

app.use(compression());

//app.use(cache(cacheTime));
apicache.options({
  debug: true,
  enabled: true,
  statusCodes: {
    include: [200],
  },
});

app.use('/api', cache(cacheTime), (req, res) => {
  if (!checkPreviewAllowed(req, res)) {
      return;
  }
  req.apicacheGroup = cacheGroupKey;
  proxy.web(req, res, {target: targetUrl});
});
```

1. Call /api/merchant/de => ``` [apicache] group detected "internal"
 [apicache] adding cache entry for "/api/merchants/de" @ 5 minutes - 8.22sec```
=> json is shown
2. Call /api/merchant/de => ```[apicache] sending cached (memory-cache) version of /api/merchants/de - 0ms```
=> HTTP Error Code 330 ERR_CONTENT_DECODING_FAILED

If I delete app.use(compression()); it start working again with route caching. 

Header for global caching on Firefox:
```
cache-control:max-age=300
connection:close
Content-Encoding:gzip
content-type:application/json
date:Wed, 22 Nov 2017 16:03:42 GMT
server:Apache
transfer-encoding:chunked
Vary:Authorization, Accept-Encoding
x-powered-by:PHP/5.6.31-1~dotdeb+7.1
```
Header for route caching on Firefox:
```
apicache-store:memory
apicache-version:1.1.0
cache-control:max-age=300
connection:close
content-encoding:gzip
content-type:application/json
date:Wed, 22 Nov 2017 16:03:51 GMT
server:Apache
transfer-encoding:chunked
Vary:Authorization, Accept-Encoding
x-powered-by:PHP/5.6.31-1~dotdeb+7.1
```

Header for global caching on Chrome:
```
x-powered-by	PHP/5.6.31-1~dotdeb+7.1
date	Wed, 22 Nov 2017 16:07:13 GMT
server	Apache
Vary	Authorization, Accept-Encoding
cache-control	max-age=300
connection	close
transfer-encoding	chunked
content-type	application/json
Content-Encoding	gzip
```
Header for route caching on Chrome:
```
x-powered-by	PHP/5.6.31-1~dotdeb+7.1
date	Wed, 22 Nov 2017 16:07:37 GMT
server	Apache
Vary	Authorization, Accept-Encoding
cache-control	max-age=300
connection	close
transfer-encoding	chunked
content-type	application/json
content-encoding gzip
apicache-store	memory api
cache-version	1.1.0
```

**Comment by kwhitley** [comment]
Hey @elodingens - sorry for the long delayed response on this!  Have you been able to solve it by now?  If so, what was the solution?  I've tried to make this work with `compression()`, and there *should* be no difference between using it as a global use statement or as middleware in an individual route.

I'll take a look though!

**Comment by elodingens** [comment]
Sry, no i was not able to fix ist. Could you reproduce it?
