### ISSUE TITLE
Cache grouping is using runtime memory, instead of Redis

### ISSUE THREAD

**Issue by anguelov** [kwhitley/apicache#126]
When I use redis for caching, cache grouping is still using runtime memory.
This creates inconsistencies when running a application in cluster mode, as only one instance of the application will have the grouping names / indexes. 

In my opinion, when using redis for caching, cache grouping must also use redis.

**Comment by kwhitley** [comment]
Will be addressed in future store implementation.  Thanks for the feedback!
