### ISSUE TITLE
post request is not cached properly 

### ISSUE THREAD

**Issue by harryyuanfeng** [kwhitley/apicache#128]
```
router.post('/earning', cache('5 minutes'), function(req, res, next) {
    var somedata = req.body.somedata;
    res.json({somedata:somedata});
})
```

here is how I used it. But when body data change, response should be different, but return the same data to the front end.

**Comment by nickvido** [comment]
You can use custom `appendKey` method in config.

```
const crypto = require('crypto')

let cache = apicache
  .options({
    appendKey: (req, res) => {
      // hash the request body as the key for the POST endpoint
      return req.method + crypto.createHash('sha256').update(JSON.stringify(req.body), 'utf8').digest("hex")
    }
  })
  .middleware
```

**Comment by kwhitley** [comment]
I'd recommend doing exactly what @nickvido suggests! 👍 

That said, in general a POST response would not be cached (it's not a "request", but a submission)... if someone wants to circumvent that logic, I definitely recommend writing a custom appendKey function.

**Comment by LiranBri** [comment]
for my opinion,I don't think an infrastructure library should enforce such standards. for a lot of cases, POST is the right way to go. for example, when you have large body, or for security reasons.

at the very least, the library should not allow at all to cache POST, but if it does allow- it should include the body as its part of the request and requivilant to the querystring.
