### ISSUE TITLE
Missing ioredis implementation in v1.2.0

### ISSUE THREAD

**Issue by Paic** [kwhitley/apicache#130]
Commit #125 was supposed to add ioredis support to v1.2.0 but the change made is not present in apicache.js on a fresh npm install (package.json indicate v1.2.0).
Am I missing something or did you simply forgot to update the package ?

**Comment by Paic** [comment]
I tried to apply the modification and I'm getting an `ReplyError: ERR wrong number of arguments for 'expire' command`.

I think it's due to :
https://github.com/kwhitley/apicache/blob/12ed3dd17d5cbbf578143b269e467d16be9b4efa/src/apicache.js#L122
ioredis is not expecting any callback

**Comment by Rauttis** [comment]
It should work with a callback also. Looks like expireCallback will be undefined with the default settings, which is what ioredis seems to be upset about. One of the open PRs seems to fix the issue: https://github.com/kwhitley/apicache/pull/117/files#diff-2a8238e1f061f7bb1a70104e481b79ffR131

**Comment by ZsoltMaslanyi** [comment]
Just want to confirm the issue. Fresh npm install, version 1.2.0 and the change is not present in the sourcecode.

**Comment by mluberry** [comment]
Using ioredis, I also get the same error (`ReplyError: ERR wrong number of arguments for 'expire' command`)

**Comment by kwhitley** [comment]
Thanks for the discussion everyone, and sorry for the long delayed fix - this has [hopefully] been taken  care of in v1.2.2 86cdfac as of today.  Please test and verify for me!  I'll be happy to reopen this if it's still failing, but closing this for now...
