### ISSUE TITLE
Feat: TypeScript Support - DefinitelyTyped

### ISSUE THREAD

**Issue by danielsogl** [kwhitley/apicache#136]
## Add type definitions for TypeScript

I created type definitions for apache and created a PR at DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25225#issuecomment-383494036

**Comment by kwhitley** [comment]
Thanks @danielsogl!  Pardon my ignorance of the subject, but do we need to do anything on the apicache end of this?  Closing this for now, but if so, I'll re-open and let's start a discussion!

**Comment by danielsogl** [comment]
Yes, you don't have to change anything. But you could add a note to the README that TypeScript users can install the typings with `npm i -D @types/apicache`.

**Comment by kwhitley** [comment]
@danielsogl Done! Updated in the repo, and will carry on to NPM in the next release/patch.

👍
