### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by reggiezhang** [kwhitley/apicache#147]
Hi,

var apicache = require('apicache');
let cacheWithRedis = apicache
  .options({ redisClient: client })
  .middleware;

meet such error during startup:

TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at syncOptions (/workspace/working_copy/gallery/node_modules/apicache/src/apicache.js:252:14)
    at ApiCache.options (/workspace/working_copy/gallery/node_modules/apicache/src/apicache.js:466:7)

happend within:
function syncOptions() {
    for (var i in middlewareOptions) {
      // add below code can avoid exception, but I don't know why only me has such error.
      if (!middlewareOptions[i].options) {
        middlewareOptions[i].options = {};
      }
      //  end
      Object.assign(middlewareOptions[i].options, globalOptions, middlewareOptions[i].localOptions)
    }
  }

My environment is nodejs 8.12.0 and expressjs 4.16.4

BRs
Reggie

**Comment by kwhitley** [comment]
You are instantiating the redis client first right?
```js
import redis from 'redis'
let client = redis.createClient()

// then you can use your previous code
```

If not, that will not work as `client` has not been defined....

**Comment by mayconmesquita** [comment]
I have the same issue.

@kwhitley The error is happening using Redis or not.

I reopened the issue here with screenshot and code here: #192 

_Node_ v11.10.1, _Express_ v4.14.0, _apicache_ v1.5.3
