### ISSUE TITLE
Returning `false` from toggle function on cached resource sends not response

### ISSUE THREAD

**Issue by apascal** [kwhitley/apicache#148]
Hi,

We use `apicache` to cache routes of an app, but only when users fulfil certain conditions, such as not having signed cookies (or any condition that could vary in time for different requests on the same resource).
The reason is that the result is intended to be specific for such users. When a user has signed cookies, we do not want to cache nor return the cached resource if it exists.

However the problem is that any user without cookies requesting the resource will add the resource to the cache, but when a second user with signed cookies asks for the same resource, **and the ressource is still cached**, `apicache` never returns the backend response.

Simplified code, to be called once without signed cookies, and once with signed cookies:
```
import apicache from 'apicache'
const cache = apicache.middleware

app.use(cookieParser())
// NB: in real life specific cookies would be targeted
const onlyWithoutSignedCookies = (req, res) => !req.signedCookies;
const cacheWhenAnonymous = cache('5 minutes', onlyWithoutSignedCookies)
app.use(cacheWhenAnonymous);
```

The code ends in:
https://github.com/kwhitley/apicache/blob/master/src/apicache.js#L220
with a `return false` instead of a response.

I wonder if this could have to do with the removed part of the code below which apparently was intended to skip the cache altogether:
https://github.com/kwhitley/apicache/blob/master/src/apicache.js#L394
```
// REMOVED IN 0.11.1 TO CORRECT MIDDLEWARE TOGGLE EXECUTE ORDER
// if (typeof middlewareToggle === 'function') {
//   if (!middlewareToggle(req, res)) return bypass()
// } else if (middlewareToggle !== undefined && !middlewareToggle) {
//   return bypass()
// }
```
I don't know what the side effect was, maybe it should be made clear that `toggleMiddleware` purpose is solely to test the `response` for adding a cache entry, not to test the `request` for serving the cached entry, as this can lead to the response not being delivered.

Maybe another `toggle(req, res): Boolean` function could be used for the specific purpose of bypassing the cache altogether ?

Adrien

**Comment by dbrekalo** [comment]
Any idea when will this be on main release?
