### ISSUE TITLE
Extend caching engine. 

### ISSUE THREAD

**Issue by bubunyo** [kwhitley/apicache#150]
Is it possible to extend and implement a custom cache engine? Eg, to implement a simple caching layer that doesn't use either redis of mem-cache.

**Comment by kwhitley** [comment]
I welcome the addition if you can create a PR with a clear/elegant abstraction interface that each one uses!

Ideally I'd have a structure similar to the following

```js
import apicache from `apicache` // perhaps defaults to memory version (below)
import apicache from `apicache/memory`
import apicache from `apicache/redis`
import apicache from `apicache/yourCustomMemoryStore`
```

**Comment by kwhitley** [comment]
This will be core to the next version, so any feedback on what/how you'd like a store implemented would be welcome.
