### ISSUE TITLE
Feature: fallback on memory cache when redis is down

### ISSUE THREAD

**Issue by apascal** [kwhitley/apicache#158]
I am not sure if this should be handled by `apicache` or outside of the middleware.
This is not the same as #71

We use `apicache` in a real world application, with a `ioredis` client as the apicache store.

The only downside of using redis, is that if redis is not available when apicache starts, or worse, if it goes down while the rest of the express app is still up, `apicache` will delay the responses forever and eventually crash, when it could use its internal memory cache as a fallback.

@kwhitley do you have any thoughts on how this should be handled ? I have not succeeded in changing the redis client to `false` once the middleware is instantiated, so in my opinion it can only be handled inside the middleware.

**Comment by kwhitley** [comment]
Hmmm... that's a good point. 

What's an easy way to test for Redis?  try/catch on the actual store commands?

This would be yet another validation of the future idea of separate store implementations with matching interfaces.  Then you could even create a cache with a single or multiple layers of cache stores, for pass through or fallback.

I think in the current tightly integrated implementation with all the dirty logic checks, it would be difficult to add this without essentially doubling all those checks. :(

**Comment by apascal** [comment]
Thanks for the answer, I'll close this as there is not much to be done currently.
