### ISSUE TITLE
Negative max-age value

### ISSUE THREAD

**Issue by apascal** [kwhitley/apicache#165]
Since ^1.4.0 and beaaa70 there is a critical bug in the computation of the value of max-age.

Depending on how slow the time of the cached expiration is, compared to actually evaluating the remaining max-age, the `max-age` value can be negative (usually -1 because of the `toFixed(0)`).

In our real world application it has happened several times in a matter of days, with a 60 seconds cache duration. We had to revert to `apicache@^1.3.1`.

FYI a `max-age=-1` header is interpreted by a CDN as an infinite cache...

**Comment by kwhitley** [comment]
Closed by #166 - Thanks for your patience @apascal and thanks for the fix @killdash9!
