### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by razmjo-netlinks** [kwhitley/apicache#171]
Hello,

on version `1.4.0`, I receive this message.

<img width="1099" alt="Screen Shot 2019-07-20 at 9 51 37 AM" src="https://user-images.githubusercontent.com/47707531/61574364-fd89d200-aad3-11e9-9578-2f51f1333b75.png">

**Comment by kwhitley** [comment]
Sorted as of `1.5.2`! 🥇
