### ISSUE TITLE
Any thought to exposing a way to view memory cache stats?

### ISSUE THREAD

**Issue by dptoot** [kwhitley/apicache#172]
The README states that the memory cache is an instance of [memory-cache](https://github.com/ptarjan/node-cache).  It looks like this has been removed for a local implementation.  We would really like to set up some local monitoring and a stats method display hits/misses/sizes would be really useful.   Has there been any thought into adding this?

**Comment by kwhitley** [comment]
Just merged in @killdash9's killer PR on this, exposing a `apicache.getPerformance()` function to return per-route cache stats, hit rate, etc.  Will release a minor shortly!
