### ISSUE TITLE
lodash@1.3.1 is deprecated, can it be upgraded to remove this warning?

### ISSUE THREAD

**Issue by Markavian** [kwhitley/apicache#18]
When installing `apicache` as a dependency via npm:
```npm WARN deprecated lodash@1.3.1: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0```

**Comment by AlexChesters** [comment]
:+1:

**Comment by kwhitley** [comment]
Thanks for the catch @Markavian!

Have updated to `^4.11.1`
