### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by havlan** [kwhitley/apicache#183]
Thanks for a great library! I'm looking for some clarity about invalidation of caches.
Does this library support only invalidation by expiration (ttl)? Or are there some ways of manually doing invalidation? (Especially relevant for api endpoints which performs joins across multiple tables)

**Comment by jdolearydl** [comment]
Just call apicache.clear():
From the readme:
> apicache.clear([target]) - clears cache target (key or group), or entire cache if no value passed, returns new index.
