### ISSUE TITLE
please update npm to v 0.0.13

### ISSUE THREAD

**Issue by thucnc** [kwhitley/apicache#19]

**Comment by brendanyounger** [comment]
+1 !!!
apicache is nearly useless without appendKey support

**Comment by davebaol** [comment]
Couldn't agree more

**Comment by davebaol** [comment]
Someone should close this issue.
Thanks for publishing 0.0.14 on npm.

**Comment by kwhitley** [comment]
Thanks @davebaol - missed it after publishing!
