### ISSUE TITLE
Q: Does it caches request-response for multiple users hitting the node app in same host?

### ISSUE THREAD

**Issue by xploreraj** [kwhitley/apicache#191]
Hi, Thanks for the library. I am using this for get information which I think does needs to be looked into DB every time. I have got a query though.

Does it ensures same response is returned for specified period for same URL but being requested by different users? 

Is this an alternative to caching at backend service?

![image](https://user-images.githubusercontent.com/6238056/73726962-89083f00-4756-11ea-810f-6eef2038f08f.png)

**Comment by jonchurch** [comment]
This middleware caches responses using the [`originalUrl`](https://expressjs.com/en/api.html#req.originalUrl) property as the key. 

It does not know anything about users specifically, it simply checks the `originalUrl` property of an incoming request, and if that key is stored in the cache, it will return the value associated with that key.

I hope that helps ❤️

**Comment by xploreraj** [comment]
Sure. Thanks.
