### ISSUE TITLE
Missing documentation on valid values for cache duration

### ISSUE THREAD

**Issue by mskutle** [kwhitley/apicache#199]
I can't find documentation on what values you can use for cache duration.
In your examples you use _cache('5 minutes')_, and I have tried cache('1 week') which works well.

However, _cache('1 month')_ doesn't seem to be valid.

It would be really nice to have an overview of all possible values :)

**Comment by kwhitley** [comment]
@mskutle this is a result of the limits of `setTimeout`, as outlined here:
https://github.com/kwhitley/apicache/issues/208

That said, long duration support is about to rolled out, meaning any of these (and longer) **should** work fine afterwards.  Hang in there!
