### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by nmors** [kwhitley/apicache#22]
Hi all.

I heard that there was a future plan to implement redis as the cache store. Is anyone working on this at the moment?

I am running a clustered express api and the cache needs to be common across all processes.

I will make this change and provide a PR if nobody else is going to soon.

Ill provide an optional parameter which is a redis client instance. So redis client will be maintained outside of the module. Is this okay? Else i could include the redis client inside apicache and simply pass options instead.

Let me know which way is preferred

Thanks 
Nathan

**Comment by nmors** [comment]
@blazerguns

**Comment by nmors** [comment]
Seems like nobody is. You will get a PR from me in next couple weeks

**Comment by kwhitley** [comment]
Thanks man, sorry for the communication/merge delays!!! PR was much appreciated though!
