### ISSUE TITLE
apicache not supported on Node 14

### ISSUE THREAD

**Issue by LukeXF** [kwhitley/apicache#226]
`error apicache@1.5.3: The engine "node" is incompatible with this module. Expected version ">=6.2.0 <13". Got "14.2.0"`

Is there a specific reason why this can't run on node 13/14? Or any solution on how to use this with node 14?

**Comment by LukeXF** [comment]
Downgrading from `1.5.3` to `1.5.2` fixes this issue.

**Comment by imnotjames** [comment]
Yeah - does look like in the `1.5.3` release that restriction was added but unclear the reasoning.  It doesn't seem related to the redis fix included in the release?

**Comment by imnotjames** [comment]
https://github.com/kwhitley/apicache/pull/212#issuecomment-631217276 Looks like this is why?

**Comment by kwhitley** [comment]
@imnotjames is correct... under Node 14, the restify and redis tests break down hard:
![image](https://user-images.githubusercontent.com/865416/96635748-e7c01980-12e1-11eb-93c9-ba84bb6749d6.png)
![image](https://user-images.githubusercontent.com/865416/96635800-f8708f80-12e1-11eb-8ef4-a77a95a46b44.png)
![image](https://user-images.githubusercontent.com/865416/96635834-045c5180-12e2-11eb-87cb-34ca6007d888.png)

**Comment by kwhitley** [comment]
As I don't use restify or redis in my projects, I'd hoped someone else would spearhead the fixes there as I have no easy way to test these beyond the test suite.

In hindsight, and should apicache realistically get to a proper v2, it'll drop baked-in support for either, instead allowing any store mechanism with a standard interface to be plugged into apicache - making it backend agnostic.  This would allow other to author/maintain the plugins, and apicache to simply focus on firing the appropriate cache calls and handling the response/headers side of things.

**Comment by kwhitley** [comment]
The next problem is that I have moved on past express in the last year and will likely focus on serverless (CloudFlare Workers) for the near future, and thus library focus will be on improved tooling in that workflow (Example: https://www.npmjs.com/package/itty-router).  If someone would like to collaborate on a v2 of apicache, I'd be happy to discuss and pass the torch if the vision aligns! 👍

**Comment by kwhitley** [comment]
Fixed as of now @ `1.6.2`

Thanks very much for everyone's patience!
