### ISSUE TITLE
Fails to cache 'content-encoding' header

### ISSUE THREAD

**Issue by agolden** [kwhitley/apicache#27]
Apicache is failing to cache the 'content-encoding' header.  As a result, when you retrieve something from cache that is gzipped, the browser (or whoever is viewing the document from cache) does not realize that the content should be decompressed before display.

**Comment by kwhitley** [comment]
Great point @agolden... I'll be doing a ground-up refresh of the library before long (it's aging and the code is ugly), and the lack of response flexibility has concerned me (and others) for some time!

**Comment by kwhitley** [comment]
Should be fixed as of `v0.5.0` which hijacks the `response.end` method and makes no assumptions about headers (clones full headers at time of final send, no matter what they were)
