### ISSUE TITLE
bypass for errors

### ISSUE THREAD

**Issue by thom-nic** [kwhitley/apicache#3]
I'm using apicache to cache an expense request to an upstream server that sometimes times out.  However when the upstream request _does_ timeout, I want to return an error response and **not** cache it so that the next time I will retry the upstream operation again.

So it's not clear how to say from my route handler post-apicache middleware, "don't cache the request this time."  I've tried adding `apicache.clear(req.url);` in my handler when I return my error response but that doesn't appear to work.

**Comment by uncedric** [comment]
it would be great if we could have an option to save in cache only  responses with status 200, or add a handler function on the start configuration

**Comment by aaronryden** [comment]
:+1:

**Comment by kwhitley** [comment]
Will sort this when I return to the States (and reliable internet) in a few weeks! Thanks for the patience guys!

~
Kevin

**Comment by kwhitley** [comment]
See docs and/or Wiki for statusCode caching bypasses.  This has been added!
