### ISSUE TITLE
Strange behavior (v0.0.14) duplicate add cache message, strange order of messages, cache does not timeout

### ISSUE THREAD

**Issue by Amri91** [kwhitley/apicache#31]
Hi,

These are the messages I am getting in the console. The calls are roughly 1 second apart.

[api-cache]: returning redis cached version of "/firstApi?param=value/appendKey=value"
[api-cache]: path "/firstApi?param=value/appendKey=value" not found in cache
[api-cache]: adding cache entry for "/firstApi?param=value/appendKey=value" @ 5000 milliseconds
[api-cache]: adding cache entry for "/firstApi?param=value/appendKey=value" @ 5000 milliseconds
[api-cache]: returning redis cached version of "/firstApi?param=value/appendKey=value"
[api-cache]: returning redis cached version of "/firstApi?param=value/appendKey=value"
[api-cache]: returning redis cached version of "/firstApi?param=value/appendKey=value"
[api-cache]: returning redis cached version of "/firstApi?param=value/appendKey=value"
[api-cache]: returning redis cached version of "/firstApi?param=value/appendKey=value"
[api-cache]: returning redis cached version of "/firstApi?param=anotherValue/appendKey=anotherValue"
[api-cache]: path "/firstApi?param=anotherValue/appendKey=anotherValue" not found in cache
[api-cache]: adding cache entry for "/firstApi?param=anotherValue/appendKey=anotherValue" @ 5000 milliseconds
[api-cache]: adding cache entry for "/firstApi?param=anotherValue/appendKey=anotherValue" @ 5000 milliseconds

What do you think the issue might be?

**Comment by nmors** [comment]
Hi @Amri91 , thanks for reporting this!

Can you please post your redis client configuration and api-cache options you are passing in?

Would be great if you could give a little extra context too. Or anything else I can use to replicate the issue. I've just added support for redis, so it is not well tested at this point.

I'll gladly help troubleshoot & fix this, but I will need some more info :) Thanks

**Comment by Amri91** [comment]
@nmors 
**cache configurations**
debug: true,
defaultDuration: 1000 * 60 * 5
appendKey: some values

**redis configurations**
Using [redis](https://www.npmjs.com/package/redis)
server:127.0.0.1
port:6379

**redis server**
[redis for windows](https://github.com/MSOpenTech/redis)

**operating system**
Windows 10

**Comment by kwhitley** [comment]
Any luck on this @Amri91?

At a glance, those look like some pretty weird request paths!

**Comment by kwhitley** [comment]
@Amri91 Feel free to reopen if this behavior still occurs in `v0.7.0`+
