### ISSUE TITLE
Not respecting hostname

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [kwhitley/apicache#32]
Hello,

I think a server serving multiple virtual hosts should not cache requests from other virtual hosts.
Each host should have a separate cache.

What do you think ?

**Comment by kwhitley** [comment]
Correct me if I'm wrong, but given that scenario, wouldn't only the routing to the virtual host (running the node instance) be handling/seeing/caching its own requests?  This should naturally  prevent the route/cache pollution...

I'm not a server ops guy though, so anyone feel free to pipe in?

**Comment by GuillaumeLeclerc** [comment]
I think it was a legitimate use case but I forgot it, I think I found a workaround. What you say makes perfectly sense. I don't remember the original purpose of my question sorry.

**Comment by kwhitley** [comment]
Great, thanks @GuillaumeLeclerc - feel free to re-open if you run into the issue again!
