### ISSUE TITLE
Duplicated entries at index

### ISSUE THREAD

**Issue by jesuslinares** [kwhitley/apicache#36]
Hi,

why when a cached URL is expired, it is still in the index?.

Example:
`router.get('/', cache(2 seconds), function(req, res)`

Now, I do 4 request, and getIndex returns:
```
"all": [
      "/agents",
      "/agents"
    ],
    "groups": {
      "agents": [
        "/agents",
        "/agents"
      ]
    }
```

why there are 2 requests ("/agents") instead of just 1 request?. all the request showed in getIndex are in memory?. It seems like old cached requests are not deleted from the memory.

Thanks.

**Comment by dazld** [comment]
Having the same issue, seems that when a key is expired in memcache, the index data structure isn't cleaned up, hence duplicate keys.

**Comment by kwhitley** [comment]
Thanks @jesuslinares & @dazld - Have added automatic index expiry (the internal memory-cache/redis were already handling their own expiration)
