### ISSUE TITLE
Trying to cache for more than 30 days causes all misses

### ISSUE THREAD

**Issue by liddiard** [kwhitley/apicache#40]
The source of issue appears to be that setTimeout breaks on any millisecond value that doesn't fit in a 32-bit int. See: ptarjan/node-cache#35

If there's no easy workaround (I suspect not), it'd be good to mention this limitation in the docs since it looks like the apicache code is [designed to handle longer time periods like months/years](https://github.com/kwhitley/apicache/blob/e961f4914bd341eeb432a76f38ee64f761e151c2/lib/apicache.js#L13).

As an aside it would be nice to have a "cache indefinitely until cleared" option – my original use case for setting such a long time in the first place. memory-cache supports it by [omitting the `time` argument](https://github.com/ptarjan/node-cache#put--functionkey-value-time-timeoutcallback).

**Comment by kwhitley** [comment]
Thanks for the catch @liddiard!  I'll make a note of that in the docs...

**Comment by kwhitley** [comment]
Limited to max (1 month) in `v0.5.0` to prevent this behavior, and removed years from the units because who would do that anyway?  :)
