### ISSUE TITLE
Clearing all with cached entries

### ISSUE THREAD

**Issue by cjfurelid** [kwhitley/apicache#43]
@kwhitley 
Running the apicache with no parameters in the .clear() function gives that 'this.delete is not a function' at \apicache\lib\memory-cache.js:54:26

**Comment by kwhitley** [comment]
Thanks for the catch @cjfurelid! I'll investigate this morning (and add test coverage for it).

**Comment by cjfurelid** [comment]
No worries, I was able to solve it by just declaring 'this' as an instance outside the Object on that line if that is to any help :-)

**Comment by kwhitley** [comment]
Thanks for the bugfix (you've been added to the README)!  Couldn't replicate this in my own tests, but I added test coverage and passed in the `this` context to the `.forEach()`.  Mind testing it in your application using **v0.3.5** to see if it solved your issue?

Cheers~

**Comment by Blackbaud-SteveBrush** [comment]
Thanks, I was having this same issue; upgrading to 3.5 helped!

**Comment by kwhitley** [comment]
Glad to hear it!  Closing issue then~
