### ISSUE TITLE
Problem with Redis and cache key groups

### ISSUE THREAD

**Issue by scambier** [kwhitley/apicache#46]
With the memory store, this code works:
```js
const apicache = require('apicache');
const cache = apicache.middleware;

router.get('/someroute', cache('1 hour'), (req, res) => {
  req.apicacheGroup = 'cachekey'; // Set cache
  // ...
});

router.post('/someroute/', (req, res) => {
  apicache.clear('cachekey'); // Clear cache
  // ...
});
```

But if I set the redisClient option, the `apicache.clear('cachekey')` function does not clear the cache as expected:

```js
const redis = require('redis').createClient();
apicache.options({redisClient: redis}); // This breaks
```

**Comment by kwhitley** [comment]
Thanks for the catch... I just added redis tests in my monkeypatch branch, and will extend it to cover cache groups while I solve that.

Should go out later today as v0.5.0
