### ISSUE TITLE
TODO: Test with gzip compression

### ISSUE THREAD

**Issue by kwhitley** [kwhitley/apicache#51]
Encoding issues with gzip on subsequent calls

**Comment by kwhitley** [comment]
Done!

**Comment by timelf123** [comment]
When I have this middleware enabled with `compression` all requests time out. Any ideas/workarounds? Currently frontend proxy does not gzip so we were doing it in app

```
  app.use(compression({level: 9}));
```

**Comment by kwhitley** [comment]
@timelf123 What apicache version are you running?  This was a known issue with earlier versions...

**Comment by timelf123** [comment]
This is on `0.8.3`
