### ISSUE TITLE
some confusion about x-apicache-force-fetch & x-apicache-bypass

### ISSUE THREAD

**Issue by Red-Lv** [kwhitley/apicache#53]
I find the two header have the same effect. what's the purpose of this two different headers?
And at the same time, the x-apicache-force-fetch header will make the server block because it does not call next()。

**Comment by msieurtoph** [comment]
@Red-Lv (and anyone interested in those headers ;) )

The original behaviors were not the same.
Take a look at this PR

https://github.com/kwhitley/apicache/pull/220
