### ISSUE TITLE
add apicache headers to response

### ISSUE THREAD

**Issue by kwhitley** [kwhitley/apicache#6]
In particular, for testing sake and the ability to tell at a glance (from the client) if you're seeing a cached version or not - I'm going to embed (and namespace) some apicache response headers:

Thinking of something along the lines of:

``` js
{
  apicache: 'v0.1.0',         // on cached responses only
  apicache-duration: '1 week' // because who reads in milliseconds?
}
```

**Comment by AlexChesters** [comment]
:+1:
