### ISSUE TITLE
Caching POST and breaking on Body change

### ISSUE THREAD

**Issue by VishalWaman** [kwhitley/apicache#64]
We have an Express Node Api which incudes diffrent controllers for API using Routes.Index.js

So when we Implement ApiCache it seems to return same Response even if we change request Parameter..

E.g :  
**Login API : ApiCache implemented**
When  we request first time we get data from API with Credentials like Username : **aFirst** and Password : **aFirst**
When  we request SECOND time we get data from API with Credentials like Username : **aSecond** and Password : **aSecond**

**It should Refresh cache when we change Input Parameter for GET and POST API.**

Thanks.

**Comment by kwhitley** [comment]
Apicache by default uses the request URL (full) as the basis of a cache key. If this doesn't change, a cache hit will occur on the second request.  That said, I wouldn't recommend putting  apicache in front of any login/auth requests, or any admin requests (e.g. PUT, DELETE, POST), as it should not cache data that changes per request/session.  You may also take advantage of the appendKey option to help differentiate cached responses.  Does this help?

If not, I'll need to see example requests+responses highlighting the issue better!

Cheers

**Comment by VishalWaman** [comment]
OK, That is helpful.
