### ISSUE TITLE
Should If-None-Match Headers Be Respected?

### ISSUE THREAD

**Issue by svozza** [kwhitley/apicache#69]
As it stands, the apicache middleware breaks Express's automatic handling of etags when the client supplies an `If-None-Match` header. I'm presuming it's something to do with overiding `res.end` but either way this is a useful feature that can reduce data sent to the client, which is especially useful in bandwidth constrained scenarios like mobile apps. It's a shame to have to chose between reducing traffic to the backend or payloads to the client. Here's a failing test case:

```js
it('respects if-none-match header', function() {
        var app = mockAPI.create('10 seconds')

        return request(app)
          .get('/api/movies')
          .expect(200)
          .then(function(res) {
            return res.headers['etag']
          })
          .then(function(etag) {
            return request(app)
              .get('/api/movies')
              .set('if-none-match', etag)
              .expect(304)
              .expect('etag', etag)
          })
      })
```

**Comment by harikm-dmart** [comment]
I have as similar problem as well. When an If-None-Match header is supplied with the request, the cache is ignored although the intent is to use the cached content and check the ETAG.

**Comment by kwhitley** [comment]
@svozza @harikm-dmart - This has been fixed, and @svozza I added your (perfect) test into the suite!

**Comment by svozza** [comment]
Brilliant. Thanks mate!
