### ISSUE TITLE
Serve Different sub-domains

### ISSUE THREAD

**Issue by AmitM30** [kwhitley/apicache#70]
Hi,

So, I am trying to serve different sub-domain from the same express server. The subdomains are language and country based (en-sa, ar-sa ...) and am parsing the context into a jade file before sending to client.

The issue is, as obvious, the caching is route based so for homepage it serves the same html for all sub-domains, '/'.

How do you think I can handle this to cache different homepages for different sub-domains ?

**Comment by kwhitley** [comment]
@AmitM30 I hadn't really anticipated multiple domains from the same express entry point, but that's a completely valid issue...  I'll patch tomorrow!

**Comment by AmitM30** [comment]
Thanks. will wait !

**Comment by AmitM30** [comment]
@kwhitley any updates on this?

**Comment by AmitM30** [comment]
Hey,

Resolved the issue with by adding the endpoint to apicache **options**:
`apicache.options({ appendKey: ['headers', 'x-original-host'] });`

**Comment by franciscop** [comment]
Hey @AmitM30, thanks for your proposed solution. It guided me and I ended up doing something very similar; since Express will parse the common headers for the host and put them into a single variable, I did:

```js
const middleware = apicache.options({
  appendKey: (req) => req.hostname,
}).middleware;
```
