### ISSUE TITLE
redis error handling

### ISSUE THREAD

**Issue by jwickens** [kwhitley/apicache#71]
Hi every once in a while my redis server is unresponsive, which generates the below error. Since its not caught and handled it stops express. Can this be caught in this apicache? 

```js
events.js:160
throw er; // Unhandled 'error' event
^

Error: Redis connection to someredisserver.com failed - read ECONNRESET
at exports._errnoException (util.js:1026:11)
at TCP.onread (net.js:569:26)
``

**Comment by idealley** [comment]
As a quick fix you could use `forever` or `nodemon` it will restart automatically express if you have a crash. 

Alternatively you can also use the cluster module, and start a new child process when one dies.
