### ISSUE TITLE
Cannot read property 'x-apicache-bypass' of undefined

### ISSUE THREAD

**Issue by mwkrieger** [kwhitley/apicache#77]
Hi, 

Having a bit of an issue when trying to implement. My sample code is as follows: 

```
var express = require('express');
var apicache = require('apicache');
apicache.options({ debug: true });
var cache = apicache.middleware();
var router = express.Router();

router.get('/test', cache('1 hour'), function (req, res) {
//code in here
};

```
When the app loads, I get the error 'Cannot read property 'x-apicache-bypass' of undefined'.

Any idea on what I might be missing?

**Comment by kwhitley** [comment]
Hey @mwkrieger - you just need to not immediately execute the middleware function during your assignment.  It should be:

```js
var cache = apicache.middleware;
```

...instead.  It's just a reference to the built in middleware function that you would pass to your route.  There are lots of ways to write this of course, and if you wanted a single time duration through your entire routes, you could do something like:

```js
var cached = apicache.middleware('1 hour');

router.get('/test/', cached, function(req, res) {
  // code here
})
```

notice that `middleware` only gets executed once in both cases (just in different spots).  The return value of that execution is a true middleware `function(req, res, next)` signature, so if you accidentally execute it twice, there are no longer request/response objects captured (which apicache uses internally of course)

Hope that helps!
