### ISSUE TITLE
Index is not rebuilding after app restart

### ISSUE THREAD

**Issue by tsubik** [kwhitley/apicache#78]
When app restart cache index is not rebuilt. That is a problem when using redis cache, because without index I cannot clear the cache and I have to wait for items to expire in redis. Maybe index should be stored in redis too? Also if you are scaling to have many application instances, the index should be shared between them.

**Comment by Nakira** [comment]
Hello,

I have the same issue but in another context.
As I have multiples instances of my app, each instance has it own index.
I can only observe that apicache with redis is not entirely stateless.

I need to fix this ASAP, so if I find a quick fix, i'll share.

**Comment by Nakira** [comment]
a quick and dirty fix : https://github.com/kwhitley/apicache/pull/82

**Comment by tsubik** [comment]
Yeah, also spotted that problem.

**Comment by sergeant-q** [comment]
@tsubik I believe we might be hitting this bug you mentioned, where one app instance is not clearing the cache entry and the other one is.

I am trying to understand how would this be happening if we are using one redis server as our caching store and both app instances are pointing to the same server? We have them running in elastic beanstalk behind a load balancer.

Has anyone else reported this issue or is there a proposed fix in the pipeline?

**Comment by kwhitley** [comment]
Closing for now, but any update on what was happening, @d3vild06? Handling app crash gracefully needs to be a requirement of future store implementations.  My goal for the next pass is to decouple the middleware mechanics from the store implementation, to allow for 3rd party store support without cluttering the main codebase, for example:

```js
import apicache from 'apicache/redis'
import apicache from 'apicache/memory'
```

...etc
