### ISSUE TITLE
Cache groups & index only work in debug mode

### ISSUE THREAD

**Issue by ade5** [kwhitley/apicache#8]
In my testing I am finding that the index object and the cache groups (apicacheGroup) are both only populated in debug mode.

Is this intentional?  It seems to me that the console.log should be behind the 'if debug mode', but not the other code in that section.  Perhaps the two 'if' statements are the wrong way around?

Either that or I am doing something wrong...

Thanks in advance for any feedback.

**Comment by stelios313** [comment]
Can confirm that i run into this issue today, it seems to me that the if statements are wrong for the case of the last bypass attempt. Can we get a fix on this?

**Comment by Webcascade** [comment]
+1

**Comment by 4F2E4A2E** [comment]
Thank you so much for this fix! It worked! (yei)

**Comment by Webcascade** [comment]
Please close this issue.
