### ISSUE TITLE
Information Request: How do I add an extra Item to the Route (Like Company ID)

### ISSUE THREAD

**Issue by franky-continu** [kwhitley/apicache#83]
Hi, I have the same routes for different companies and users. We get the Company ID (and the user id in other cases) from a security token given on login. 

And then we filter by this Company ID taken from a token that comes in a HEADER on the REQUEST.

How could I add that (a mondodb ID)? so something like this `52911feb8f819b571000000b`

Is there something like:

```javascript
import apicache from 'apicache'
let cache = apicache.middleware

app.use(cache('5 minutes'))

// routes are automatically added to index, but may be further added
// to groups for quick deleting of collections
app.get('/api/articles', (req, res) => {
  req.apicacheKey = '{5720f4980882091000b66c40}/api/articles'
  req.apicacheGroup = req.params.collection
  res.json({ success: true })
})


```

**Comment by franky-continu** [comment]
Could this be resolved if I place the company-id to the `req` object and then add appendKey array item 'company_id' for instance?

**Comment by kwhitley** [comment]
> Could this be resolved if I place the company-id to the req object and then add appendKey array item 'company_id' for instance?

Yes, this should work, and would probably be better than forcing the key manually.  Let me know if you get things sorted!
