### ISSUE TITLE
Make redis client be interchangable

### ISSUE THREAD

**Issue by Balgorn** [kwhitley/apicache#95]
Hey just started using apicache, awesome so far. My problem is our production server is running on AWS with Elasticache (which as a default config is an redis-cluster) so my question is. Could it be possible to swap out the client to something like `ioredis` which supports cluster. 

The code currently breaking at first glance is:
`            return sendCachedResponse(res, JSON.parse(obj.response))`
because the result from ioredis is slightly different.

**Comment by kwhitley** [comment]
Mind explaining the differences?  We can either roll this into the current version (if possible), or save it for version 1.0.0 (that should allow custom plugins to enable all sorts of user-enabled stores)

**Comment by Balgorn** [comment]
So one of the most important features of `ioredis` is the usage of Redis in Cluster Mode and TLS support (only redis client to my knowledge which can do that) For instance the standard config for redis on AWS is with cluster mode on.  It has also some convenience features like key prefixing which is also supported by  `apicache` .

**Comment by kwhitley** [comment]
Thanks @Balgorn! I'm adding it to the list for 1.0.0, but I may put in a hacky solution for it before then (e.g. 0.10.0)

**Comment by fabiel-leon** [comment]
& redis pool, how to do it?

**Comment by w-** [comment]
hi. is there an update on the status of compatibility between `ioredis` and `apicache`?

thanks

**Comment by GoingFast** [comment]
same question^

**Comment by kwhitley** [comment]
Can't believe I left this ticket open for so long... this has long since been addressed by @Rauttis (added ioredis support)

### Example
```js
import Redis from 'ioredis';
import apicache from 'apicache';
const redis = new Redis(6379, '127.0.0.1');
const router = express.Router();

const cache = apicache.options({
  redisClient: redis
}).middleware;

const onlyStatus200 = (req, res) => res.statusCode === 200;

const cacheSuccesses = cache('5 minutes', onlyStatus200);

router.get('/cats', cacheSuccesses, async (req, res, next) => {
  cats.allCats(req, res, next);
});
```
