### ISSUE TITLE
Invalid example of middleware toggle usage

### ISSUE THREAD

**Issue by josalmi** [kwhitley/apicache#96]
The readme contains an example Middleware toggle usage here: https://github.com/kwhitley/apicache#use-with-middleware-toggle-for-fine-control

However, in reality toggle middleware is executed before request is passed to the next middleware (See: [apicache.js#L282](https://github.com/kwhitley/apicache/blob/master/src/apicache.js#L282), therefore status code will always be 200 while executing the toggle middleware in both of the endpoint listed in example. Status codes include options should be used instead for caching 200 responses only. 

The toggle middleware functionality might be working as intended in which case the example is wrong or this could be a bug and the example should be working.

**Comment by kwhitley** [comment]
I'll look into this @josalmi - if nothing else, this is definitely something to add to a future release (pre/post route passes for caching)... will try and see if I can work something in the existing [dated] architecture in the meantime...

**Comment by kitce** [comment]
I am having the same issue.

Will it be fixed in the next version?

**Comment by kwhitley** [comment]
I'm working on a fix now!  Should be going out in `0.11.1` tonight/tomorrow

**Comment by kwhitley** [comment]
@josalmi @kitce @huhuime
Fixed in [apicache v0.11.1](https://www.npmjs.com/package/apicache) (releasing to NPM  tonight)

Thanks for bringing it to our attention!
