### ISSUE TITLE
update apicache in npm to v 0.8.8

### ISSUE THREAD

**Issue by saikarthikreddyginni** [kwhitley/apicache#98]

**Comment by crysislinux** [comment]
v0.8.7 does not work well with node 8 due to the header problem. v0.8.8 seems fix the problem. we really need it in npm. Thanks.

**Comment by kwhitley** [comment]
@crysislinux We are waiting for @svozza's [fix](https://github.com/restify/node-restify/issues/1429) to be merged into the [node-restify](https://www.npmjs.com/package/node-restify) codebase so it can pass the tests.  I'm wrapping several other small updates/fixes into the patch as well.  Should be any day now!

**Comment by crysislinux** [comment]
@kwhitley thanks. seems the fix got merged now. Now wait a new node-restify release 🙏

**Comment by kwhitley** [comment]
Solved by release v0.9.0 - thanks all!
