### ISSUE TITLE
HOWTO/FIX: Ellipse (framework): no content-type on cached data

### ISSUE THREAD

**Issue by yetzt** [kwhitley/apicache#99]
i am caching json containing unicode characters. in the cached version, those characters get broken, because the content-type header is not set when delivering data from the memory-cache.

**Comment by yetzt** [comment]
my bad, it's an incompatibility between this and [ellipse](https://github.com/ellipse-js/ellipse), since ellipse does not set `res._headers` and apicache expects this to contain the headers.

**Comment by kwhitley** [comment]
@yetzt Have a solution for this or should I close?  What does ellipse set (header-wise)?

**Comment by yetzt** [comment]
i found a workaround:
```
app.use(function(req, res, next){
	res.header = res.set;
	res._headers = res.headers;
	next();
});
```

solution would be eiter apicache using `res.set` and `res.headers` or ellipse providing `res.header` and `res._headers` with a release. see also ellipse-js/ellipse#1

**Comment by kwhitley** [comment]
Hey man - unfortunately although I'd love to support all the frameworks out there, I've gotta pick and choose my battles (based on userbase/downloads) to keep the module clean(ish) and less fragile.  For now I'd recommend sticking to your fix, but it's definitely something I'll keep in mind for v1.0.0 (extensible to other frameworks and stores via plugins).

I basically want to make apicache extremely flexible/programmable to allow for users to morph it easily into any environment without compromising the easy/lightweight final middleware usage.

**Comment by yetzt** [comment]
thanks anyway, apicache is very helpful (would have written something like it if it didn't exist).
